allow_screenshot: true
context_category: ''
hot_key: <ctrl>+<shift>+a
keyboard_recording: true
music_enabled: false
user_info:
  Age: '13'
  Country: korean
  Interest: game
  Job: developer
  Location: seoul
