name: Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update apt-get
        run: |
          sudo apt-get update
      - name: Install gcc
        run: |
          sudo apt-get install gcc
      - uses: actions/setup-java@v4 # for konlpy
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install Python 3.10
        run: uv python install 3.10
      - name: Install Venv
        run: uv venv
      - name: Install Dependencies
        run: uv sync
      - name: Upgrade pyOpenSSL
        run: |
          uv pip install --upgrade pyOpenSSL
      - name: Install test dependencies
        run: |
          uv pip install pytest-xdist
      - name: Run tests
        run: |
          uv run python -m pytest -o log_cli=true --log-cli-level=INFO -n auto tests/
